#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import webapp2
import logging
#from Restaurants import Restaurants
import json
from array import array
from google.appengine.ext import ndb

class Restaurants(ndb.Model):
    name = ndb.StringProperty()
    #Address = ndb.StringProperty()
    lng = ndb.StringProperty()
    lat = ndb.StringProperty()
    #comment = ndb.StringProperty()
    
    
class MainHandler(webapp2.RequestHandler):
    def get(self):
        
        pos=Restaurants()
        job=self.request.get('fetch')
        counter=1
        s="save"
        r="ret"


        #if job == s
        pos.name=self.request.get('name')
        #address=self.request.get('address')
        pos.lng=self.request.get('lng')
        pos.lat=self.request.get('lat')
        #coment=self.request.get('comment')

        pos.put()
        
        #if job == r
        n=Restaurants.query().count(limit=None)
        
		#rest_list=Restaurants.query().fetch(1)
		#self.response.write(rest_list)
        for i in range(0,n):
        	rest_list=Restaurants.query().fetch(1,offset=i)
        	self.response.write(str(rest_list) + '\n')
        	i=i+1
        
        
        
        
		
app = webapp2.WSGIApplication([
    ('/', MainHandler)
], debug=True)

